version: "3"

networks:
  lappy:

services:
  app:
    networks:
      - lappy
    build: ./fastapi
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - mongodb

  mongodb:
    networks:
      - lappy
    image: mongodb:latest
    restart: always
