version: "3"

networks:
  lappy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "11.0.2.0/24"

services:
  app:
    networks:
      lappy:
        ipv4_address: 11.0.2.2
    build: .
    restart: always
    ports:
      - "8004:8004"
    depends_on:
      - mongodb

  mongodb:
    networks:
      lappy:
        ipv4_address: 11.0.2.3
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - "27017:27017"
      
